# Generated by Django 2.2.17 on 2020-12-10 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='building',
        ),
        migrations.RemoveField(
            model_name='device',
            name='scenes',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='building',
        ),
        migrations.RemoveField(
            model_name='measuringdevice',
            name='building',
        ),
        migrations.AlterField(
            model_name='room',
            name='icon',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='icon',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='SceneDeviceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_scenes_states', to='devices.Device')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_devices_states', to='devices.Scene')),
            ],
            options={
                'unique_together': {('device', 'scene')},
            },
        ),
    ]
