# Generated by Django 2.2.17 on 2020-12-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20201210_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scene',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
