# Generated by Django 2.2.17 on 2020-12-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20201212_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measure_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measuring_device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='device_measurement', to='devices.MeasuringDevice'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DailyMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_date', models.DateTimeField(auto_now=True)),
                ('measure_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('measuring_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.MeasuringDevice')),
            ],
        ),
    ]
