# Generated by Django 2.2.17 on 2020-12-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20201230_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeasurement',
            name='measure_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measure_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
