# Generated by Django 2.2.17 on 2021-01-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20201230_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='state_value',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scenedevicestate',
            name='state_value',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ControlParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=500)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_control_parameters', to='devices.Room')),
            ],
            options={
                'unique_together': {('room', 'parameter')},
            },
        ),
    ]
