# Generated by Django 2.2.17 on 2021-01-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20210109_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlparameter',
            name='parameter_value',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
