# Generated by Django 2.2.17 on 2021-01-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_controlparameter_parameter_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='state_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
