# Generated by Django 2.2.17 on 2021-01-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20210110_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='state_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='scenedevicestate',
            name='state_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
