# Generated by Django 2.2.17 on 2021-01-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20210110_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
